### ISSUE TITLE
Modcount is broken

### ISSUE THREAD

**Issue by ghost** [Mango0x45/speedrunbot-plusplus#18]
![IMG_20210709_105029](https://user-images.githubusercontent.com/75923279/125025275-3138da80-e0a4-11eb-8f15-7a2b2c51ab41.jpg)

what is the reason for this error and is it possible to correct it?

**Comment by Mango0x45** [comment]
> what is the reason for this error

I accidentally broke it in a [recent commit](https://github.com/Mango0x45/speedrunbot-plusplus/commit/84cceb3281ffcd699fae9ce5628b80a2c263c04c#diff-7ad10f539e0670ab73e4dadca03bf2e75458add4ae5dc822e1b8a18c57def703) by forgetting to add the players name when calling `fmt.Printf()`. Thanks for the report, it's fixed now.
